People/Models/FamilyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace People.Models
{
    public class FamilyViewModel
    {


        public List<Children> GetChildrens { get; set; }
        public List<Sibling> GetSiblings { get; set; }

        
    }
}

People/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace People.Models
{
    public class Person
    {
        public Person()
        {
            Children = new List<Children>();
            Siblings = new List<Sibling>();
        }

        public int PersonId { get; set; }

        [Display(Name="First Name")]
        public string FirstName { get; set; }

        [Display(Name= "Last Name")]
        public string LastName { get; set; }

        public int Age { get; set; } = 0;
        public string Gender { get; set; }
        public bool IsAlive { get; set; } = true;
        public int SpouseId { get; set; }
        public List<Children> Children { get; set; }
        public List<Sibling> Siblings { get; set; }

    }
}

People/Models/PersonViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace People.Models
{
    public class PersonViewModels
    {


       public int  PresonId { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public int Age { get; set; } = 0;
        public string Gender { get; set; }
        public bool IsAlive { get; set; } = true;
        
        public string SpouseName { get; set; }



    }
}




 


    

People/Controllers/ChildrenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using People.Data;
using People.Models;

namespace People.Controllers
{
    public class ChildrenController : Controller
    {
        private readonly PeopleContext _context;

        public ChildrenController(PeopleContext context)
        {
            _context = context;
        }


        public IActionResult Kids(int id)
        {
            List<Children> childrens = new List<Children>();
             childrens = _context.Children.Where(k => k.PersonId  == id).ToList();

            return View(childrens);


        }


        public IActionResult Family(int id, int sid)
        {
            List<Person> persons = new List<Person>();
            persons = _context.Persons.Where(o => o.SpouseId == id).ToList();
            List<Children> childrens = new List<Children>();
            childrens= _context.Children.Where(c => c.PersonId==id ).ToList();
            return View("~/Views/Children/index.cshtml", childrens);
            
        }


        // GET: Children
        public async Task<IActionResult> Index()
        {
            return View(await _context.Children.ToListAsync());
        }

        // GET: Children/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var children = await _context.Children
                .FirstOrDefaultAsync(m => m.ChildrenId == id);
            if (children == null)
            {
                return NotFound();
            }

            return View(children);
        }

        // GET: Children/Create
        public IActionResult Create(int id)
        {
            ViewBag.id = id;
            return View();
        }

        // POST: Children/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChildrenId,FirstName,LastName,Age,Gender,IsAlive,PersonId")] Children children)
        {
            if (ModelState.IsValid)
            {
                _context.Add(children);
                await _context.SaveChangesAsync();
                // return RedirectToAction(nameof(Index));
                return RedirectToAction("MarriedCouples", "People");
            }
            return View(children);
        }

        // GET: Children/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var children = await _context.Children.FindAsync(id);
            if (children == null)
            {
                return NotFound();
            }
            return View(children);
        }

        // POST: Children/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ChildrenId,FirstName,LastName,Age,Gender,IsAlive")] Children children)
        {
            if (id != children.ChildrenId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(children);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChildrenExists(children.ChildrenId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(children);
        }

        // GET: Children/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var children = await _context.Children
                .FirstOrDefaultAsync(m => m.ChildrenId == id);
            if (children == null)
            {
                return NotFound();
            }

            return View(children);
        }

        // POST: Children/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var children = await _context.Children.FindAsync(id);
            _context.Children.Remove(children);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChildrenExists(int id)
        {
            return _context.Children.Any(e => e.ChildrenId == id);
        }
    }
}

People/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using People.Data;
using People.Models;
using People.Controllers;


namespace People.Controllers
{
    public class PeopleController : Controller
    {
        private readonly PeopleContext _context;

        public PeopleController(PeopleContext context)
        {
            _context = context;
        }

        // Get Person Family Tree
        public IActionResult GetFamilyTree(int id)
        {
                 var a = _context.Persons.Where(o => o.PersonId == id).Include(o => o.Children).Include(o => o.Siblings).FirstOrDefault();

                Person person = _context.Persons.Find(id);
                string fullName = person.FirstName + " " + person.LastName;
                ViewBag.person = fullName;           
                Person p2 = _context.Persons.Single(j => j.SpouseId == id);
                string spouseName = p2.FirstName + " " + p2.LastName;
                ViewBag.SpouseName = spouseName;
                List<Children> children = _context.Children.Where(o => o.PersonId == id).ToList();
                if (children == null)
                {
                    children = new List<Children>();
                }
                List<Sibling> siblings = _context.Siblings.Where(o => o.PersonId == id).ToList();
                if (siblings == null)
                {
                    siblings = new List<Sibling>();
                }
                ViewBag.Children = children;
                ViewBag.Siblings = siblings;
                return View("~/Views/FamilyTree/FamilyTreeView.cshtml");
                 
            
        }

         public IActionResult Family (string SearchString)
         {
          
                var people = from m in _context.Persons.Where(p => p.SpouseId>0)
                             select m;
            
                if (!String.IsNullOrEmpty(SearchString))
                {
                     people = people.Where(s => s.FirstName.Contains(SearchString));

                }
                       
                return View(people.ToList());
         }       

        
        public async Task<IActionResult> MarriedCouples()
        {
            List<Person> people = new List<Person>();
             people = await _context.Persons.Where(o => o.SpouseId >0).ToListAsync();
            List<PersonViewModels> personViews = new List<PersonViewModels>();
           
            
            foreach (Person p in people)
            {
                PersonViewModels pvm = new PersonViewModels();
                pvm.PresonId = p.PersonId;
                pvm.FirstName = p.FirstName;
                pvm.LastName = p.LastName;
                pvm.Age = p.Age;
                pvm.Gender = p.Gender;
                pvm.IsAlive = p.IsAlive;
                Person person = _context.Persons.FirstOrDefault(o => o.PersonId == p.SpouseId);
                pvm.SpouseName = person.FirstName + " " + person.LastName;

                personViews.Add(pvm);

            }

            return View("~/Views/People/Spouse.cshtml", personViews.ToList());
        }

        // Confirm marriage and save in db/ dislplay spouse name in view
        public async Task<IActionResult> Confirmed(int id1, int id2)
        {
            Person firstPerson = await _context.Persons.FindAsync(id1);
            Person secondPerson = await _context.Persons.FindAsync(id2);
            firstPerson.SpouseId = secondPerson.PersonId;
            secondPerson.SpouseId = firstPerson.PersonId;
             _context.SaveChanges();

            List<Person> people = await _context.Persons.ToListAsync();

            List<PersonViewModels> personViews = new List<PersonViewModels>();

            foreach (Person person in people)
            {
                PersonViewModels pvm = new PersonViewModels();
                pvm.PresonId = person.PersonId;
                pvm.FirstName = person.FirstName;
                pvm.LastName = person.LastName;
                pvm.Age = person.Age;
                pvm.Gender = person.Gender;
                pvm.IsAlive = person.IsAlive;
                Person marriedPerson = _context.Persons.FirstOrDefault(o => o.PersonId == person.SpouseId);
                pvm.SpouseName = marriedPerson.FirstName + " " + marriedPerson.LastName;

                personViews.Add(pvm);

            }
            return View("~/Views/People/Spouse.cshtml", personViews.ToList());
        }
        
        // Find List of Opposit Gender
        public async Task<IActionResult> Marry(string fName, int id, string gender, int spouseId)
        {

            ViewBag.id = id;
            
             
            List<Person> oppGenderPersonUnMarried = new List<Person>();
            if (gender != null && gender.ToLower() == "male")
            {
                oppGenderPersonUnMarried = await _context.Persons.Where(o => o.IsAlive == true && o.SpouseId == 0 && o.Gender == "Female").ToListAsync();

            }

            else
            {
                oppGenderPersonUnMarried = _context.Persons.Where(o => o.IsAlive == true && o.SpouseId == 0 && o.Gender == "male").ToList();
            }

            return View(oppGenderPersonUnMarried);
        }

        // GET: People who are singles
        public async Task<IActionResult> Index()
        {
            List<Person> people = new List<Person>();
            people= await _context.Persons.Where (o => o.SpouseId == 0).ToListAsync();
            return View(people);
            
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Add Single Person in db
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonId,FirstName,LastName,Age,Gender,IsAlive")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonId,FirstName,LastName,Age,Gender,IsAlive")] Person person)
        {
            if (id != person.PersonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.PersonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Persons.FindAsync(id);
            _context.Persons.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ShowAllDetails(int personid)
        {
            var a = _context.Persons.Where(o => o.PersonId == personid).Include(o => o.Children).Include(o => o.Siblings).FirstOrDefault();
            ViewBag.AllDetails = a;
            return View("~/Views/FamilyTree/AllDetailsView.cshtml");

        }

        private bool PersonExists(int id)
        {
            return _context.Persons.Any(e => e.PersonId == id);
        }
    }


}

People/Views/People/Confirmed.cshtml
@model IEnumerable<People.Models.Person>
@{
    ViewData["Title"] = "Confirmed";
}

<h1>Married Couples</h1>
<h2>Congratulations! </h2>
<p>Here you go this is list of Married Couple</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpouseId)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.SpouseId > 0)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Age)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>


                        @Html.DisplayFor(modelItem => item.SpouseId)

                    </td>
                    <td>
                        <a asp-controller="Children" asp-action="Family" asp-route-id="@item.PersonId" asp-route-sid="@item.SpouseId">Children</a> |
                        <a asp-action="Spouse" asp-route-sid="@item.SpouseId" asp-route-id="@item.PersonId"> Spouse</a> 

                    </td>
                </tr>
            }
        }
    </tbody>
</table>

People/Views/People/Create.cshtml
@model People.Models.Person

@{
    ViewData["Title"] = "Create";
}

 
<h4>Add Single Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            


            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAlive" /> @Html.DisplayNameFor(model => model.IsAlive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

People/Views/People/Delete.cshtml
@model People.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsAlive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsAlive)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

People/Views/People/Details.cshtml
@model People.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsAlive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsAlive)
        </dd>
         
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PersonId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

People/Views/People/Family.cshtml
@model IEnumerable<People.Models.Person>
@{
    ViewData["Title"] = "Family";
}

 
<h1 class="bg-primary text-center mt-4">Choose a Person to See Family Tree</h1>

<p>
    <a class="btn btn-outline-success btn-lg" asp-action="Create">Create New</a>
</p>

<form asp-controller="People" asp-action="Family">
    <p>
        First Name: <input type="text" name="SearchString" formmethod="get">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpouseId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAlive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @*@if (item.SpouseId == 0)*@
            //{
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpouseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsAlive)
                </td>
                <td>

                    <a class="btn btn-success btn-sm" asp-controller="Siblings" asp-action="Siblings" asp-route-id="@item.PersonId">Sibling</a>|
                    <a class="btn btn-dark btn-sm" asp-controller="Children" asp-action="Kids" asp-route-id="@item.PersonId">Children</a> |

                    <a class="btn btn-info btn-sm" asp-controller="People" asp-action="GetFamilyTree" asp-route-name="@item.FirstName" asp-route-id="@item.PersonId">Family Tree</a>
                     
                </td>
            </tr>
            //}
        }
    </tbody>
</table>

People/Views/People/FamilyTree.cshtml
@model IEnumerable<People.Models.PersonViewModels>
@{
    ViewData["Title"] = "FamilyTree";
}

 

<h1>Family Tree</h1>

<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.PresonId)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpouseName)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {


            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.PresonId)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpouseName)
                </td>

                <td>
                    @*<a asp-action="Edit" asp-route-id="">Edit</a> |
                        <a asp-action="Details" asp-route-id="">Details</a> |
                        <a asp-action="Delete" asp-route-id="">Delete</a> |*@
                    <a asp-controller="Children" asp-action="Kids" asp-route-id="@ViewBag.id">Children</a>

                </td>
            </tr>


        }
    </tbody>
</table>

People/Views/People/Spouse.cshtml
@model IEnumerable<People.Models.PersonViewModels>



@{
    ViewData["Title"] = "Spouse";
}

<h1 class="bg-primary text-center">Married Couples with Spouse Name</h1>
 
<h2>Congratulations! </h2>
<p>Here you go this is list of Married Couple</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PresonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpouseName)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {


            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PresonId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpouseName)
                </td>

                <td>
                    @* <a asp-action="Edits" asp-route-id="@item.PresonId" asp-route-spousename="@item.SpouseName" asp-route-firstname="@item.FirstName">Edit</a> |
                                 <a asp-action="Details" asp-route-id="">Details</a> |
                        <a asp-action="Delete" asp-route-id="">Delete</a> |*@

                    @*<a asp-action="Detail" asp-route-id="@item.PresonId" asp-route-spousename="@item.SpouseName" asp-route-firstname="@item.FirstName">Details</a> |*@

                    @*<a asp-controller="Children" asp-action="Kids" asp-route-id="@ViewBag.id">Children</a>*@
                    <a class="btn btn-info" btn-sm asp-controller="Children" asp-action="Create" asp-route-id="@item.PresonId">Add Children</a>

                </td>
            </tr>


        }
    </tbody>
</table>